### ISSUE TITLE
API return codes have changed.

### ISSUE THREAD

**Issue by rasjani** [grinsted/plugin.video.telkkarista#3]
there is no "response" field anymore in returned query, its now "code"  and data returned is now full api name. you can check my plugin's "apibase.py" for a bit more details.

**Comment by grinsted** [comment]
Thank you. I will check your code, and commit this when i get back home.

Best
Aslak

On Fri, Jun 19, 2015 at 2:38 PM, Jani Mikkonen notifications@github.com
wrote:

> there is no "response" field anymore in returned query, its now "code" and
> data returned is now full api name. you can check my plugin's "apibase.py"
> for a bit more details.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/grinsted/plugin.video.telkkarista/issues/3.

## 

Dr. Aslak Grinsted

Centre for Ice and Climate http://www.iceandclimate.nbi.ku.dk/, Niels
Bohr Institute, University of Copenhagen
Juliane Maries Vej 30 (Room 243), 2100 Copenhagen Ø, Denmark
http://www.glaciology.net | twitter: @agrinsted
http://twitter.com/agrinsted | phone: +45 353-20510
